### ISSUE TITLE
Derivation of equation for LIF f-I curve

### ISSUE THREAD

**Issue by Mark-Kramer** [Mark-Kramer/BU-MA665-MA666#29]
#28 The function solves an equation, but where does that equation come from?

**Comment by Mark-Kramer** [comment]
Here's a solution, using Mathematica @YesterdaySam 

[Solve LIF FI curve.pdf](https://github.com/Mark-Kramer/BU-MA665-MA666/files/2447073/Solve.LIF.FI.curve.pdf)

**Comment by cwconroy** [comment]
[LIF_ByHand.pdf](https://github.com/Mark-Kramer/BU-MA665-MA666/files/2447788/LIF_ByHand.pdf)

Basically the same as above, but done by hand so algebra a little more clear?

I followed along with the notes included in the code but filled in solutions for my own elucidation

**Comment by Mark-Kramer** [comment]
@cwconroy Excellent!
